name: FactionPlotWorld
main: mixpa.qq514518274.FactionPlotWorld
version: 1.0.0
description: A simple Plot Faction world generator.
softdepend: [LegacyFactions]
load: STARTUP
commands:
  plot:
    description: 插件的主命令
    aliases: [p]